Iter15
vRylsky07/DevOpsMetricsProject pull request #15
Opened 2024-09-22 12:15 UTC by vRylsky07

2024-09-24 08:31 UTC, nburunova requested changes

2024-09-24 08:31 UTC, nburunova commented on internal/configs/configs.go
> +	rLimit := flag.Int("rlimit", 3, "limits of request workers")
ключ должен быть -l по заданию

2024-09-24 08:31 UTC, nburunova commented on internal/agent/agent.go
> +	mSender, err := sender.CreateSender(cfg, 10)
почему именно 10?

2024-09-24 08:31 UTC, nburunova commented on internal/funcslib/funcslib.go
> +	return string(sign) == string(MakeSignSHA(body, key))
есть специальнвая функция https://pkg.go.dev/crypto/hmac#Equal , может ее использовать?

2024-09-24 08:31 UTC, nburunova commented on internal/sender/sender.go
>  		if sStg.cfg.PollInterval == -1 {
это точно надо при каждом цикле проверять? может один раз где-то проверить?

2024-09-24 08:31 UTC, nburunova commented on internal/sender/sender.go
>  		defer ticker.Reset(time.Duration(sStg.cfg.ReportInterval) * time.Second)
останавливаем тикер при каждом выходе из функции? почему такое решение?
Может пусть тикер дальше тикает, не нужно его каждый раз останавливать и запускать? По задумке тикеры нужны для того, чтобы отмерять тики . Их останавливают, только когда приложение закрывается.

2024-09-24 08:31 UTC, nburunova commented on internal/sender/sender.go
> +		client := http.Client{}
каждый раз создаем клиента. Можно ли один раз создать и переиспользовать?

2024-09-24 08:31 UTC, nburunova commented on internal/server/helperstructs.go
> +
наврное случайно в ПР попал закоментированный код

2024-10-12 19:21 UTC, vRylsky07 commented
Интерфейс для хранилища MetricsRepository переместил в отдельный пакет common, т.к. используется в нескольких пакетах, судя по информации из гугла в данном случае это является хорошей практикой если потребителей этого интерфейса несколько

2024-10-14 10:48 UTC, merged