Iter5
vRylsky07/DevOpsMetricsProject pull request #5
Opened 2024-03-05 20:30 UTC by vRylsky07

2024-03-16 15:08 UTC, Bazys requested changes

2024-03-16 15:08 UTC, Bazys commented on internal/server/server.go
> +	coreStg *storage.MemStorage
в сендере ожидаешь интерфейс, а тут почему реализацию?

2024-03-16 15:08 UTC, Bazys commented on internal/server/server.go
> +func StartServerOnPort() {
в main эта функция выглядит как `server.StartServerOnPort()` вот прям масло маслянное.
Может достаточно `server.Start()` тем более уже не указываешь порт

2024-03-16 15:08 UTC, Bazys commented on cmd/server/main.go
> -	storage.InitMemStorage()
ты сдаешь код на проверку первый раз, я должен проверить все инкременты в одном PR. А у тебя сейчас получается что какой то инкремент уже в main

2024-03-17 11:02 UTC, vRylsky07 commented on cmd/server/main.go
> -	storage.InitMemStorage()
ну вроде поправил, сейчас в 5ом PRе все коммиты с самого начала

2024-03-19 19:04 UTC, Bazys approved these changes
для первого спринта всё отлично. 
По мере продвижения по курсу требования будут усложняться, поэтому не удивляйся, если буду делать замечания на то, что пропустил в начале.

2024-03-19 19:30 UTC, merged